# Generated by Django 2.1.5 on 2019-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('plan_to_migrate', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=256)),
                ('server_names', models.TextField(null=True)),
                ('create_app_response', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfraServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('asasd', 'asasd'), ('asdasd', 'asdasd'), ('asdasd', 'asdasd'), ('aifi-2', 'Aifi-2')], max_length=1000)),
                ('env_name', models.CharField(max_length=1000)),
                ('stack', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('no_of_instance', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4')], max_length=256)),
                ('instance_type', models.CharField(max_length=256)),
                ('ssh_location', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerAwsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentId', models.CharField(max_length=1000)),
                ('configurationId', models.CharField(max_length=1000)),
                ('hostName', models.CharField(max_length=1000)),
                ('osName', models.CharField(max_length=1000)),
                ('osVersion', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('timeOfCreation', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
            ],
        ),
    ]
