# Generated by Django 2.1.5 on 2019-02-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infradatabases',
            name='create_env',
        ),
        migrations.AddField(
            model_name='infradatabases',
            name='env_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aws.InfraServiceInfo'),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(choices=[('asasd', 'asasd'), ('asdasd', 'asdasd'), ('Aifi-2', 'Aifi-2'), ('ec2-test', 'ec2-test'), ('ec2-second', 'ec2-second'), ('Testing2', 'Testing2')], max_length=1000),
        ),
    ]
