# Generated by Django 2.1.5 on 2019-02-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('instance_type', models.CharField(max_length=1000)),
                ('instance_number', models.CharField(max_length=1000)),
            ],
        ),
    ]
