# Generated by Django 2.1.5 on 2019-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_auto_20190131_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('plan_to_migrate', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=256)),
            ],
        ),
    ]
