# Generated by Django 2.1.5 on 2019-02-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_auto_20190207_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmigrations',
            name='app_name',
            field=models.CharField(choices=[('asasd', 'asasd'), ('asdasd', 'asdasd'), ('Aifi-2', 'Aifi-2'), ('ec2-test', 'ec2-test'), ('ec2-second', 'ec2-second'), ('Testing2', 'Testing2'), ('farhaan-testing', 'farhaan-testing')], default='Null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(choices=[('MySQL', 'MySQL'), ('Oracle', 'Oracle'), ('Oracle', 'Oracle'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL'), ('Oracle', 'Oracle'), ('MySQL', 'MySQL'), ('Oracle', 'Oracle')], default='Null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(choices=[('dev', 'dev'), ('dev1', 'dev1'), ('new', 'new'), ('farees', 'farees'), ('farhaan test', 'farhaan test'), ('asdasd', 'asdasd'), ('adssa', 'adssa'), ('asdvfvd', 'asdvfvd'), ('farhaan-testing123', 'farhaan-testing123'), ('first-full-testing', 'first-full-testing'), ('asdavt2323', 'asdavt2323'), ('asdasdasdas', 'asdasdasdas'), ('cghfthft565hgd', 'cghfthft565hgd')], default='Null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_db',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_ip',
            field=models.GenericIPAddressField(default='192.168.1.2'),
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_password',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_username',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
