# Generated by Django 2.1.5 on 2019-02-05 11:47

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_staticdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticdata',
            name='description',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1000), max_length=1000, size=None),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='instance_number',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1000), max_length=1000, size=None),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='instance_type',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1000), max_length=1000, size=None),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='stack',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1000), max_length=1000, size=None),
        ),
    ]
