# Generated by Django 2.1.5 on 2019-02-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_remove_infraserviceinfo_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmigrations',
            name='app_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aws.AppsDescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='env_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aws.InfraServiceInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aws.AppsDescription'),
            preserve_default=False,
        ),
    ]
