# Generated by Django 2.1.5 on 2019-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_auto_20190207_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(choices=[('dev', 'dev'), ('dev1', 'dev1'), ('new', 'new'), ('farees', 'farees'), ('farhaan test', 'farhaan test'), ('asdasd', 'asdasd'), ('adssa', 'adssa'), ('asdvfvd', 'asdvfvd'), ('farhaan-testing123', 'farhaan-testing123'), ('first-full-testing', 'first-full-testing'), ('asdavt2323', 'asdavt2323'), ('asdasdasdas', 'asdasdasdas'), ('cghfthft565hgd', 'cghfthft565hgd'), ('farhaanpateslss', 'farhaanpateslss')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
