# Generated by Django 2.1.5 on 2019-01-31 15:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='app_names',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('appdemo', 'appdemo'), ('demosms', 'demosms'), ('tets', 'tets')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
