# Generated by Django 2.1.5 on 2019-02-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_remove_infradatabases_env_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('asasd', 'asasd'), ('asdasd', 'asdasd'), ('Aifi-2', 'Aifi-2'), ('ec2-test', 'ec2-test'), ('ec2-second', 'ec2-second'), ('Testing2', 'Testing2'), ('farhaan-testing', 'farhaan-testing')], max_length=1000)),
                ('env_name', models.CharField(choices=[('dev', 'dev'), ('dev1', 'dev1'), ('new', 'new'), ('farees', 'farees'), ('farhaan test', 'farhaan test'), ('asdasd', 'asdasd'), ('adssa', 'adssa'), ('asdvfvd', 'asdvfvd'), ('farhaan-testing123', 'farhaan-testing123'), ('first-full-testing', 'first-full-testing'), ('asdavt2323', 'asdavt2323'), ('asdasdasdas', 'asdasdasdas'), ('cghfthft565hgd', 'cghfthft565hgd')], max_length=1000)),
                ('source_ip', models.GenericIPAddressField()),
                ('source_username', models.CharField(max_length=1000)),
                ('source_password', models.CharField(max_length=1000)),
                ('source_db', models.CharField(max_length=1000)),
                ('destination_db', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(choices=[('asasd', 'asasd'), ('asdasd', 'asdasd'), ('Aifi-2', 'Aifi-2'), ('ec2-test', 'ec2-test'), ('ec2-second', 'ec2-second'), ('Testing2', 'Testing2'), ('farhaan-testing', 'farhaan-testing')], max_length=1000),
        ),
    ]
