# Generated by Django 2.1.5 on 2019-02-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_auto_20190207_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmigrations',
            name='app_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='stack',
            field=models.CharField(choices=[('ami-03787fa0594b1f151', 'ami-03787fa0594b1f151')], max_length=1000),
        ),
    ]
