# Generated by Django 2.1.5 on 2019-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_auto_20190207_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmigrations',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='destination_db',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='env_name',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_db',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_password',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_username',
        ),
        migrations.AddField(
            model_name='infracicd',
            name='app_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='infradatabases',
            name='env_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(choices=[('first_app', 'first_app')], max_length=1000),
        ),
    ]
