# Generated by Django 2.1.5 on 2019-02-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_auto_20190131_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('appdemo', 'appdemo'), ('demosms', 'demosms'), ('tets', 'tets')], max_length=1000)),
                ('env_name', models.CharField(max_length=1000)),
                ('stack', models.CharField(max_length=1000)),
                ('description', models.TextField(choices=[('', ''), ('', ''), ('', '')])),
                ('no_of_instance', models.CharField(choices=[('3', '3'), ('0', '0'), ('0', '0')], max_length=256)),
                ('instance_type', models.CharField(max_length=256)),
                ('ssh_location', models.GenericIPAddressField()),
            ],
        ),
    ]
