# Generated by Django 2.1.5 on 2019-02-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0006_auto_20190207_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmigrations',
            name='app_name',
            field=models.CharField(choices=[('first_app', 'first_app')], default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(choices=[('Oracle', 'Oracle')], default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(choices=[('testing env', 'testing env')], default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_db',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_ip',
            field=models.GenericIPAddressField(default='192.168.1.2'),
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_password',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_username',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
