# Generated by Django 2.1.5 on 2019-02-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_auto_20190207_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(choices=[('first_env', 'first_env')], max_length=1000),
        ),
    ]
