# Generated by Django 2.1.5 on 2019-02-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_auto_20190202_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=False, related_name='cities', to='aws.Country'),
        ),
    ]
