# Generated by Django 2.1.5 on 2019-02-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_auto_20190207_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cicd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicd_appname', models.CharField(max_length=1000)),
                ('repo_name', models.CharField(max_length=1000)),
                ('env_name', models.CharField(max_length=1000)),
                ('cicd_env_id', models.CharField(max_length=1000)),
                ('s3_artifact_bucket', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ec2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec2_instancetype', models.CharField(max_length=1000)),
                ('ec2_count', models.CharField(max_length=1000)),
                ('ec2_ami', models.CharField(max_length=1000)),
                ('ec2_environment', models.CharField(max_length=1000)),
                ('ec2_appname', models.CharField(max_length=1000)),
                ('ec2_environment_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rds_engine', models.CharField(max_length=1000)),
                ('rds_instance', models.CharField(max_length=1000)),
                ('rds_storage', models.CharField(max_length=1000)),
                ('rds_username', models.CharField(max_length=1000)),
                ('rds_password', models.CharField(max_length=1000)),
                ('rds_appname', models.CharField(max_length=1000)),
                ('rds_environment', models.CharField(max_length=1000)),
                ('rds_environment_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='app_name',
            field=models.CharField(choices=[('first_app', 'first_app'), ('second_app', 'second_app'), ('third_app', 'third_app')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(choices=[('Oracle', 'Oracle'), ('Oracle', 'Oracle'), ('MySQL', 'MySQL')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(choices=[('first_env', 'first_env'), ('farhaan2', 'farhaan2'), ('second', 'second')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(choices=[('first_app', 'first_app'), ('second_app', 'second_app'), ('third_app', 'third_app')], max_length=1000),
        ),
    ]
