# Generated by Django 2.1.5 on 2019-02-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_auto_20190202_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
