# Generated by Django 2.1.5 on 2019-02-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0009_auto_20190202_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsdescription',
            name='app_names',
        ),
    ]
