# Generated by Django 2.1.5 on 2019-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0009_auto_20190207_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsdescription',
            name='plan_to_migrate',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='app_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='instance_type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='no_of_instance',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='stack',
            field=models.CharField(max_length=1000),
        ),
    ]
