# Generated by Django 2.1.5 on 2019-02-03 05:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0010_remove_appsdescription_app_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsdescription',
            name='server_names',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('d-server-03gc03v3fx6lbl', 'd-server-03gc03v3fx6lbl'), ('d-server-016kgjokz5cit6', 'd-server-016kgjokz5cit6'), ('d-server-025gdq8q4enyhk', 'd-server-025gdq8q4enyhk')], default='sfdsdf', max_length=71),
            preserve_default=False,
        ),
    ]
