# Generated by Django 2.1.5 on 2019-02-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0010_auto_20190209_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicd',
            name='cicd_artifact',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='cicd',
            name='cicd_repo_http',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='cicd',
            name='cicd_repo_ssh',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='ec2',
            name='ec2_dns',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='ec2',
            name='ec2_public_dns',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='rds',
            name='rds_database',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='rds',
            name='rds_endpoint',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='rds',
            name='rds_json_username',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='app_name',
            field=models.CharField(choices=[('first_app', 'first_app'), ('second_app', 'second_app'), ('third_app', 'third_app')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(choices=[('Oracle', 'Oracle'), ('Oracle', 'Oracle'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(choices=[('first_env', 'first_env'), ('farhaan2', 'farhaan2'), ('second', 'second'), ('aifi', 'aifi'), ('aifi1', 'aifi1'), ('aifi-test3', 'aifi-test3'), ('testing-phase', 'testing-phase')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(choices=[('first_app', 'first_app'), ('second_app', 'second_app'), ('third_app', 'third_app')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='instance_type',
            field=models.CharField(choices=[('t2.micro', 't2.micro')], max_length=256),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='no_of_instance',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4')], max_length=256),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='stack',
            field=models.CharField(choices=[('ami-03787fa0594b1f151', 'ami-03787fa0594b1f151')], max_length=1000),
        ),
    ]
