# Generated by Django 2.1.5 on 2019-02-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0011_appsdescription_server_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAwsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentId', models.CharField(max_length=1000)),
                ('configurationId', models.CharField(max_length=1000)),
                ('hostName', models.CharField(max_length=1000)),
                ('osName', models.CharField(max_length=1000)),
                ('osVersion', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('timeOfCreation', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='appsdescription',
            name='server_names',
        ),
    ]
