# Generated by Django 2.1.5 on 2019-02-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0011_auto_20190209_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmigrations',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='destination_db',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='env_name',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_db',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_password',
        ),
        migrations.RemoveField(
            model_name='createmigrations',
            name='source_username',
        ),
        migrations.AddField(
            model_name='infraserviceinfo',
            name='output_json_status',
            field=models.CharField(blank=True, default='Pending', max_length=10000),
        ),
    ]
