# Generated by Django 2.1.5 on 2019-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0012_auto_20190209_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmigrations',
            name='app_name',
            field=models.CharField(choices=[('first_app', 'first_app'), ('second_app', 'second_app'), ('third_app', 'third_app')], default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(choices=[('Oracle', 'Oracle'), ('Oracle', 'Oracle'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL'), ('MySQL', 'MySQL')], default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(choices=[('first_env', 'first_env'), ('farhaan2', 'farhaan2'), ('second', 'second'), ('aifi', 'aifi'), ('aifi1', 'aifi1'), ('aifi-test3', 'aifi-test3'), ('testing-phase', 'testing-phase')], default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_db',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_ip',
            field=models.GenericIPAddressField(default='192.168.1.2'),
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_password',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createmigrations',
            name='source_username',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
