# Generated by Django 2.1.5 on 2019-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0012_auto_20190203_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsdescription',
            name='server_names',
            field=models.TextField(null=True),
        ),
    ]
