# Generated by Django 2.1.5 on 2019-02-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0013_appsdescription_server_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsdescription',
            name='create_app_response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(choices=[('appdemo', 'appdemo'), ('demosms', 'demosms'), ('aifi-1', 'aifi-1'), ('tets', 'tets')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='description',
            field=models.TextField(choices=[('', ''), ('', ''), ('testing', 'testing'), ('testing', 'testing')], verbose_name='InfraServiceInfo'),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='no_of_instance',
            field=models.CharField(choices=[('3', '3'), ('0', '0'), ('0', '0'), ('0', '0')], max_length=256),
        ),
    ]
