# Generated by Django 2.1.5 on 2019-02-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0014_auto_20190211_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmigrations',
            name='engine_name',
            field=models.CharField(blank=True, choices=[('MySQL', 'MySQL'), ('Oracle', 'Oracle')], max_length=1000),
        ),
    ]
