# Generated by Django 2.1.5 on 2019-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0014_auto_20190203_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='app_name',
            field=models.CharField(choices=[('appdemo', 'appdemo'), ('aifi-2', 'Aifi-2'), ('demosms', 'demosms'), ('aifi-1', 'aifi-1'), ('tets', 'tets')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='description',
            field=models.TextField(choices=[('', ''), ('testing', 'Testing'), ('', ''), ('testing', 'testing'), ('testing', 'testing')], verbose_name='InfraServiceInfo'),
        ),
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='no_of_instance',
            field=models.CharField(choices=[('3', '3'), ('0', '0'), ('0', '0'), ('0', '0'), ('0', '0')], max_length=256),
        ),
    ]
