# Generated by Django 2.1.5 on 2019-02-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0015_createmigrations_engine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(max_length=1000),
        ),
    ]
