# Generated by Django 2.1.5 on 2019-02-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0017_auto_20190204_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraserviceinfo',
            name='description',
            field=models.TextField(choices=[('', ''), ('testing', 'Testing'), ('', ''), ('testing', 'testing'), ('testing', 'testing')]),
        ),
    ]
