# Generated by Django 2.1.5 on 2019-02-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0019_auto_20190212_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmigrations',
            name='destination_db',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
