# Generated by Django 2.1.5 on 2019-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0021_auto_20190212_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
