# Generated by Django 2.1.5 on 2019-02-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0024_auto_20190212_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmigrations',
            name='app_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aws.AppsDescription'),
            preserve_default=False,
        ),
    ]
