# Generated by Django 2.1.5 on 2019-02-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0025_createmigrations_app_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmigrations',
            name='app_fk',
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AppsDescription'),
        ),
        migrations.AlterField(
            model_name='createmigrations',
            name='env_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.InfraServiceInfo'),
        ),
    ]
